final List<Map<String, String>> kanjiList = [
  {"title": "母", "route": "/kanji-ibu"},
  {"title": "父", "route": "/kanji-ayah"},
  {"title": "木", "route": "/kanji-pohon"},
  {"title": "本", "route": "/kanji-buku"},
  {"title": "水", "route": "/kanji-air"},
  {"title": "火", "route": "/kanji-api"},
  {"title": "風", "route": "/kanji-angin"},
  {"title": "目", "route": "/kanji-mata"},
  {"title": "日", "route": "/kanji-hari"},
  {"title": "手", "route": "/kanji-tangan"},
  {"title": "森", "route": "/kanji-hutan"},
  {"title": "牛", "route": "/kanji-sapi"},
  {"title": "国", "route": "/kanji-negara"},
  {"title": "山", "route": "/kanji-gunung"},
  {"title": "川", "route": "/kanji-sungai"},
  {"title": "人", "route": "/kanji-orang"},
  {"title": "犬", "route": "/kanji-anjing"},
  {"title": "月", "route": "/kanji-bulan"},
  {"title": "雨", "route": "/kanji-hujan"},
  {"title": "口", "route": "/kanji-mulut"},
];
