final List<Map<String, String>> kanjiList = [
  {"title": "母", "route": "/kanji-haha"},
  {"title": "父", "route": "/kanji-chichi"},
  {"title": "木", "route": "/kanji-ki"},
  {"title": "本", "route": "/kanji-hon"},
  {"title": "水", "route": "/kanji-mizu"},
  {"title": "火", "route": "/kanji-hi"},
  {"title": "風", "route": "/kanji-kaze"},
  {"title": "目", "route": "/kanji-me"},
  {"title": "日", "route": "/kanji-hi"},
  {"title": "手", "route": "/kanji-te"},
  {"title": "森", "route": "/kanji-mori"},
  {"title": "牛", "route": "/kanji-ushi"},
  {"title": "国", "route": "/kanji-kuni"},
  {"title": "山", "route": "/kanji-yama"},
  {"title": "川", "route": "/kanji-kawa"},
  {"title": "人", "route": "/kanji-hito"},
  {"title": "犬", "route": "/kanji-inu"},
  {"title": "月", "route": "/kanji-tsuki"},
  {"title": "雨", "route": "/kanji-ame"},
  {"title": "口", "route": "/kanji-kuchi"},
];
