final List<Map<String, dynamic>> detailOkuriganaList = [
  {
    "judul": "食",
    "nama": "Makan",
    "kunyomi": ["たべる"],
    "onyomi": ["しょく"],
    "kanjiGabungan": [
      {"kanji": "食事", "furigana": "しょくじ", "arti": "Makanan"},
      {"kanji": "朝食", "furigana": "ちょうしょく", "arti": "Sarapan"},
      {"kanji": "昼食", "furigana": "ちゅうしょく", "arti": "Makan Siang"},
      {"kanji": "夕食", "furigana": "ゆうしょく", "arti": "Makan Malam"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "見",
    "nama": "Lihat",
    "kunyomi": ["みる"],
    "onyomi": ["けん"],
    "kanjiGabungan": [
      {"kanji": "見学", "furigana": "けんがく", "arti": "Kunjungan Studi"},
      {"kanji": "見物", "furigana": "けんぶつ", "arti": "Tamasya"},
      {"kanji": "意見", "furigana": "いけん", "arti": "Pendapat"},
      {"kanji": "見解", "furigana": "けんかい", "arti": "Pandangan"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "聞",
    "nama": "Dengar",
    "kunyomi": ["きく"],
    "onyomi": ["ぶん", "もん"],
    "kanjiGabungan": [
      {"kanji": "新聞", "furigana": "しんぶん", "arti": "Surat Kabar"},
      {"kanji": "聞き手", "furigana": "ききて", "arti": "Pendengar"},
      {"kanji": "新聞", "furigana": "しんぶん", "arti": "Koran"},
      {"kanji": "聞こえる", "furigana": "きこえる", "arti": "Terdengar"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "話",
    "nama": "Bicara",
    "kunyomi": ["はなす"],
    "onyomi": ["わ"],
    "kanjiGabungan": [
      {"kanji": "会話", "furigana": "かいわ", "arti": "Percakapan"},
      {"kanji": "話題", "furigana": "わだい", "arti": "Topik"},
      {"kanji": "物語", "furigana": "ものがたり", "arti": "Cerita"},
      {"kanji": "電話", "furigana": "でんわ", "arti": "Telepon"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "書",
    "nama": "Tulis",
    "kunyomi": ["かく"],
    "onyomi": ["しょ"],
    "kanjiGabungan": [
      {"kanji": "読書", "furigana": "どくしょ", "arti": "Membaca Buku"},
      {"kanji": "書類", "furigana": "しょるい", "arti": "Dokumen"},
      {"kanji": "書店", "furigana": "しょてん", "arti": "Toko Buku"},
      {"kanji": "辞書", "furigana": "じしょ", "arti": "Kamus"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "読",
    "nama": "Baca",
    "kunyomi": ["よむ"],
    "onyomi": ["どく", "とく"],
    "kanjiGabungan": [
      {"kanji": "読書", "furigana": "どくしょ", "arti": "Membaca Buku"},
      {"kanji": "読み方", "furigana": "よみかた", "arti": "Cara membaca"},
      {"kanji": "朗読", "furigana": "ろうどく", "arti": "Membaca Nyaring"},
      {"kanji": "購読", "furigana": "こうどく", "arti": "Langganan Bacaan"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "買",
    "nama": "Beli",
    "kunyomi": ["かう"],
    "onyomi": ["ばい"],
    "kanjiGabungan": [
      {"kanji": "買い物", "furigana": "かいもの", "arti": "Belanja"},
      {"kanji": "買収", "furigana": "ばいしゅう", "arti": "Akuisisi"},
      {"kanji": "買い手", "furigana": "かいて", "arti": "Pembeli"},
      {"kanji": "買い換え", "furigana": "かいかえ", "arti": "Beli Pengganti"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "売",
    "nama": "Jual",
    "kunyomi": ["うる"],
    "onyomi": ["ばい"],
    "kanjiGabungan": [
      {"kanji": "販売", "furigana": "はんばい", "arti": "Penjualan"},
      {"kanji": "売店", "furigana": "ばいてん", "arti": "Kios"},
      {"kanji": "売り切れ", "furigana": "うりきれ", "arti": "Habis Terjual"},
      {"kanji": "売買", "furigana": "ばいばい", "arti": "Jual Beli"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "立",
    "nama": "Berdiri",
    "kunyomi": ["たつ"],
    "onyomi": ["りつ"],
    "kanjiGabungan": [
      {"kanji": "独立", "furigana": "どくりつ", "arti": "Kemerdekaan"},
      {"kanji": "立場", "furigana": "たちば", "arti": "Posisi"},
      {"kanji": "起立", "furigana": "きりつ", "arti": "Berdiri"},
      {"kanji": "立食", "furigana": "りっしょく", "arti": "Makan Berdiri"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "入",
    "nama": "Masuk",
    "kunyomi": ["はいる"],
    "onyomi": ["にゅう"],
    "kanjiGabungan": [
      {"kanji": "入口", "furigana": "いりぐち", "arti": "Pintu Masuk"},
      {"kanji": "入学", "furigana": "にゅうがく", "arti": "Masuk Sekolah"},
      {"kanji": "入社", "furigana": "にゅうしゃ", "arti": "Masuk Perusahaan"},
      {"kanji": "入力", "furigana": "にゅうりょく", "arti": "Masukan (Input)"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "出",
    "nama": "Keluar",
    "kunyomi": ["でる", "だす"],
    "onyomi": ["しゅつ"],
    "kanjiGabungan": [
      {"kanji": "出口", "furigana": "でぐち", "arti": "Pintu Keluar"},
      {"kanji": "出発", "furigana": "しゅっぱつ", "arti": "Keberangkatan"},
      {"kanji": "出版", "furigana": "しゅっぱん", "arti": "Penerbitan"},
      {"kanji": "出席", "furigana": "しゅっせき", "arti": "Kehadiran"},
    ],
    "route":"/detail-okurigana",
  },
  {
    "judul": "作",
    "nama": "Buat",
    "kunyomi": ["つくる"],
    "onyomi": ["さく"],
    "kanjiGabungan": [
      {"kanji": "作業", "furigana": "さぎょう", "arti": "Pekerjaan"},
      {"kanji": "作文", "furigana": "さくぶん", "arti": "Karangan"},
      {"kanji": "制作", "furigana": "せいさく", "arti": "Produksi"},
      {"kanji": "作者", "furigana": "さくしゃ", "arti": "Penulis"},
    ],
    "route":"/detail-okurigana",
  },
];
