final List<Map<String, dynamic>> detailTest = [
  {
    "judul": "Test Hiragana",
    "soal": [
      {"pertanyaan": "Apa bunyi dari ひ?", "jawaban": "hi"},
      {"pertanyaan": "Apa bunyi dari さ?", "jawaban": "sa"},
      {"pertanyaan": "Apa bunyi dari つ?", "jawaban": "tsu"},
      {"pertanyaan": "Apa bunyi dari み?", "jawaban": "mi"},
      {"pertanyaan": "Apa bunyi dari ぬ?", "jawaban": "nu"},
      {"pertanyaan": "Apa bunyi dari け?", "jawaban": "ke"},
      {"pertanyaan": "Apa bunyi dari こ?", "jawaban": "ko"},
      {"pertanyaan": "Apa bunyi dari そ?", "jawaban": "so"},
      {"pertanyaan": "Apa bunyi dari ち?", "jawaban": "chi"},
      {"pertanyaan": "Apa bunyi dari ね?", "jawaban": "ne"},
      {"pertanyaan": "Apa bunyi dari ひゃ?", "jawaban": "hya"},
      {"pertanyaan": "Apa bunyi dari りょ?", "jawaban": "ryo"},
      {"pertanyaan": "Apa bunyi dari ふ?", "jawaban": "fu"},
      {"pertanyaan": "Apa bunyi dari ま?", "jawaban": "ma"},
      {"pertanyaan": "Apa bunyi dari ゆ?", "jawaban": "yu"},
      {"pertanyaan": "Apa bunyi dari わ?", "jawaban": "wa"},
      {"pertanyaan": "Apa bunyi dari し?", "jawaban": "shi"},
      {"pertanyaan": "Apa bunyi dari え?", "jawaban": "e"},
      {"pertanyaan": "Apa bunyi dari ら?", "jawaban": "ra"},
      {"pertanyaan": "Apa bunyi dari ぐ?", "jawaban": "gu"},
    ],
  },
  {
    "judul": "Test Katakana",
    "soal": [
      {"pertanyaan": "Apa bunyi dari カ?", "jawaban": "ka"},
      {"pertanyaan": "Apa bunyi dari サ?", "jawaban": "sa"},
      {"pertanyaan": "Apa bunyi dari ツ?", "jawaban": "tsu"},
      {"pertanyaan": "Apa bunyi dari ミ?", "jawaban": "mi"},
      {"pertanyaan": "Apa bunyi dari ヌ?", "jawaban": "nu"},
      {"pertanyaan": "Apa bunyi dari ケ?", "jawaban": "ke"},
      {"pertanyaan": "Apa bunyi dari コ?", "jawaban": "ko"},
      {"pertanyaan": "Apa bunyi dari ソ?", "jawaban": "so"},
      {"pertanyaan": "Apa bunyi dari チ?", "jawaban": "chi"},
      {"pertanyaan": "Apa bunyi dari ネ?", "jawaban": "ne"},
      {"pertanyaan": "Apa bunyi dari キャ?", "jawaban": "kya"},
      {"pertanyaan": "Apa bunyi dari リョ?", "jawaban": "ryo"},
      {"pertanyaan": "Apa bunyi dari フ?", "jawaban": "fu"},
      {"pertanyaan": "Apa bunyi dari マ?", "jawaban": "ma"},
      {"pertanyaan": "Apa bunyi dari ユ?", "jawaban": "yu"},
      {"pertanyaan": "Apa bunyi dari ワ?", "jawaban": "wa"},
      {"pertanyaan": "Apa bunyi dari シ?", "jawaban": "shi"},
      {"pertanyaan": "Apa bunyi dari エ?", "jawaban": "e"},
      {"pertanyaan": "Apa bunyi dari ラ?", "jawaban": "ra"},
      {"pertanyaan": "Apa bunyi dari グ?", "jawaban": "gu"},
    ],
  },
];
